version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "llir"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
    ports:
      - "5432:5432"

  redis:
    image: redis
    command: redis-server --requirepass dockerPasswd
    ports:
    - "6379:6379"
